Disable gradient check for linalg.eig
Both the eager and compiled versions fail with the following message
when trying to compute the grad:

    RuntimeError: linalg_eig_backward: The eigenvectors in the complex
    case are specified up to multiplication by e^{i phi}. The specified
    loss function depends on this quantity, so it is ill-defined.

I'm not sure if there's a way to adapt the OptInfo such that the grad is
computable, but we should at least check that the forward pass is
correct.

ghstack-source-id: 0de3d868d38526776020054dcdb7f4a297d33d27
Pull Request resolved: https://github.com/pytorch/pytorch/pull/109165